AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - '**/Gemfile'

Metrics/LineLength:
  Max: 90

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Enabled: false

Style/StringLiterals:
  Enabled: true
